openMF/ph-ee-env-template

- helm/ph-ee-engine/templates/connector-gsma.yml
- helm/ph-ee-engine/values.yaml
This PR consists of GSMA Connector Helm Template and Values for the same
> GSMA Connector Template

- orchestration/feel/mpesa-flow.bpmn
This is the updated version of mpesa flow. These changes are made by @SubhamPramanik. It includes updated variables name and workflow name.
> mpesa flow updated

- .gitignore
- helm/ph-ee-engine/templates/connector-ams-pesa.yml
- helm/ph-ee-engine/templates/connector-mpesa.yml
Currently single commit 0460380 contains the mpesa connector config and a4518b2 contains the pesacore connector config.
> mpesa and pesacore connector kube config added

- helm/ph-ee-engine/templates/connector-message-gateway.yaml
- message gateway mysql
- message gateway mysql config
- message gateway manifest
> message gateway manifest yaml

- PostmanCollections/Payment Hub.json
Added the collection request API
> Collection request postman collection update

- helm/ph-ee-engine/templates/zeebe-ops.yml
- orchestration/feel/mpesa-flow.bpmn
Link to the docker image: [https://hub.docker.com/r/danishfynarfin/ph-ee-zeebe-ops](https://hub.docker.com/r/danishfynarfin/ph-ee-zeebe-ops)
> Zeebe ops helm template added and mpesa flow update

- orchestration/feel/mpesa-flow.bpmn
Callback wait time updated to `90 sec` for both the mpesa and notification.
> Mpesa bpmn update

- .github/workflows/test.yaml
Updates the github actions workflow - download dependencies and lint the chart. I think there are some changes needed, but I'm not sure I could fix them properly
> add helm linter, and fixes per same

- orchestration/feel/acknowledgement-individual-workflow.bpmn
> BPMN workers update

- helm/ph-ee-engine/templates/mock_asl_oracle.yaml
- helm/ph-ee-engine/values.yaml
* Added the .yaml for `mock-oracle`.
* Added .yaml contains the script for deployment, service(cluster IP), and an ingress.
> Added mock-oracle deployment, service & ingress

- helm/ph-ee-engine/templates/connector-bulk.yaml
- helm/ph-ee-engine/values.yaml
* Override the disable-ssl variable for the bulk connector.
> Fixes #33 disabled ssl in bulk processor

- helm/ph-ee-engine/Chart.yaml
* Changed version from 1.2.0 to 1.1.15,  Error: can't get a valid version for repositories ph-ee-engine. Try changing the version constraint in Chart.yaml
> Update Chart.yaml 

- helm/ph-ee-engine/templates/mock_asl_oracle.yaml
- helm/ph-ee-engine/values.yaml
* Bug fixed in mock-oracle template.
> mock-oracle renamed to mock_oracle

- PostmanCollections/Collection OAF.postman_collection.json
- PostmanCollections/Environment/OAF UAT.postman_environment.json
- PostmanCollections/Environment/SIT.json
- PostmanCollections/Payment Hub.json
* Changes made to include X-CorrealtionId in the header for following API:
-  GSMA P2P
- International Remmitance Payee
- Collection Request
- Bulk transfer older
- Bulk Transfer
- Batch Transactions
- Bulk Account Lookup
- Batch Summary
- Batch Details
- Batch Lookup Details
- Get All Batches
- Notifications Callback
- Send Message to Message Gateway
- Message gateway provider callback
@avikganguly01 and @fynmanoj : please review
> New header

- PostmanCollections/External APIs.json
* New postman collection for maintaining external APIs like SLCB, MPESA, ROASTER, PAYGOPS.
👇🏼 This is how the collection structure looks like 👇🏼. 
> Added new postman collection containing external APIs

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
* Added Kong chart in the requirement
* Added required value configuration for the OIDC connector plugin
> Added Kong configuration

- Keycloak/kong-keycloak-realm.json
- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
* Added Keycloak to requirements 
* Added Kong realm export file with configuration for OIDC
> Added Keycloak to template

- helm/ph-ee-engine/values.yaml
* Added Kong ingress annotations for ops-web consisting of OIDC plugin
> Added Kong ingress annotations for ops-web

- PostmanCollections/Environment/SIT.json
- PostmanCollections/Payment Hub.json
- added batch transfer for json api
- added postman tests to check the batch id,request id and status 
- appended the test API env variable accordingly to test newman pipeline
@fynmanoj
> Batch transfer json and postman tests

- PostmanCollections/Payment Hub.json
GSMA transaction API added to postman collection
> gsma-transaction-api

- helm/ph-ee-engine/templates/connector-channel.yaml
- helm/ph-ee-engine/templates/connector-mpesa.yaml
- helm/ph-ee-engine/values.yaml
- Ingress for paygops
- Ingress for roster
- Parameters added : 
```
{{ .Values.channel.paygops.host }}
{{ .Values.channel.roster.host }}
{{ .Values.mpesa.paygops.host }}
{{ .Values.mpesa.roster.host }}
{{ .Values.mpesa.channel.host }}
```
@fynmanoj
> Added ingress for paygops and roster

- PostmanCollections/Payment Hub.json
* Added Postman collection for new channel api and added client corrlation id in other get APIs
> Adding collection for client correaltion in get api and new channel api

- helm/ph-ee-engine/templates/connector-ams-paygops.yaml
- helm/ph-ee-engine/templates/connector-ams-roster.yaml
- added service for paygops and roster
@fynmanoj
> Service for paygops and roster

- helm/ph-ee-engine/templates/connector-ams-mifos.yaml
- helm/ph-ee-engine/templates/connector-channel.yaml
- helm/ph-ee-engine/values.yaml
Parameterising values for gsma p2p flow
> Parameterising values for gsma p2p flow

- helm/ph-ee-engine/values.yaml
Fix for enabling es and kibana without security (Please make sure superset values.yml doesnt override them)
@avikganguly01 @somanath21 
> Updating the protocol in elasticsearch and kibana

- PostmanCollections/Environment/FineractCoDevelop_environment.json
- PostmanCollections/G2P Sandbox Demo Prep.json
* Added G2P Sandbox Demo Prep.json and fineract Codevelop sandbox env json file
- [ ##] Design related bullet points or design document link related to this PR added in the description above. 
- [ ##] Updated corresponding Postman Collection or Api documentation for the changes in this PR.
- [##] Create/update unit or integration tests for verifying the changes made.
- [ ##] Add required Swagger annotation and update API documentation with details of any API changes if applicable
- [ ##] Followed the naming conventions as given in …
> G2psandbox postman collection and environment variables

- helm/ph-ee-engine/templates/operations-importer-es.yaml
- helm/ph-ee-engine/templates/zeebe-ops.yaml
- helm/ph-ee-engine/values.yaml
Fixing the es security error for importer es, kibana and zeebe ops
> Fixing the es security error for importer es, kibana and zeebe ops

- helm/ph-ee-engine/templates/connector-mojaloop-java.yaml
- helm/ph-ee-engine/values.yaml
* Added ingress template for `ph-ee-connector-mojaloop-java`.
[PHEE-183](https://fynarfin.atlassian.net/browse/PHEE-183?atlOrigin=eyJpIjoiNWM4ZmYyZGVkZTlmNDgzNWExYmQ1ZDY3NTI3YTUwMjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-183]: https://fynarfin.atlassian.net/browse/PHEE-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added ingress for mojaloop

- helm/ph-ee-engine/values.yaml
* update versions for each dependency on this release
> default-image-version-update-for-release

- helm/ph-ee-engine/templates/connector-mojaloop-java.yaml
- helm/ph-ee-engine/values.yaml
* Added env variables for switch hosts.
https://fynarfin.atlassian.net/browse/PHEE-194
> PHEE-194 switch related env variables added

- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/templates/connector-ams-mifos.yaml
- helm/ph-ee-engine/templates/connector-mojaloop-java.yaml
- helm/ph-ee-engine/values.yaml
> Added service and ingress to ams mifos 

- PostmanCollections/Payment Hub.json
- helm/ph-ee-engine/templates/connector-ams-mifos.yaml
- helm/ph-ee-engine/values.yaml
> Added Loanhost

- helm/ph-ee-engine/templates/connector-ams-mifos.yaml
> Added dfspid key value pair in template

- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/values.yaml
> release-1.4.4

- PostmanCollections/Environment/SIT.json
- PostmanCollections/Payment Hub.json
- added environment variables and params
> Environment variables and Params

- PostmanCollections/Payment Hub.json
> newman-test-fix

- helm/ph-ee-engine/templates/connector-channel.yaml
- helm/ph-ee-engine/templates/connector-mpesa.yaml
- helm/ph-ee-engine/values.yaml
- added hosts for paybill flow
> Hosts for paybill flow

- helm/ph-ee-engine/templates/connector-channel.yaml
- helm/ph-ee-engine/templates/connector-mpesa.yaml
- helm/ph-ee-engine/values.yaml
> Added hosts for paybill

- helm/ph-ee-engine/templates/connector-channel.yaml
> Updated the Container port of channel due to migration

- helm/ph-ee-engine/values.yaml
> bulk-processor-v1.4.1-added

- PostmanCollections/ph-ee-bulk-demo-5.csv
- PostmanCollections/ph-ee-bulk-demo-6.csv
> Uploaded bulk csv file for gsma

- helm/ph-ee-engine/values.yaml
> Updated the typo transfer in mojaloop

- PostmanCollections/Environment/SIT.json
- PostmanCollections/Payment Hub.json
Updated postman collection with callback url header
> Adding bulk callback url

- PostmanCollections/ph-ee-bulk-demo-11.csv
* Added mojaloop CSV file fro bulk scenario
> Added mojaloop csv file

- .env
- helm/ph-ee-engine/values.yaml
- added new variables for reporting index
> Added new variables

- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/values.yaml
> release-1.6.0

- helm/ph-ee-engine/values.yaml
Changed type for shortcode to string
- changed type of shortcode to string for paybill
> Changed type for shortcode

- helm/ph-ee-engine/templates/connector-ams-paygops.yaml
- Added null value for paygops authheader 
> Added null value for paygops authheader

- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/values.yaml
> version release update

- Kibana Visualisations/export-saved-objects.py
- steps to run the script for generating saved objects
> Steps to run the script

- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/values.yaml
Parameterised necssary values
Note:::: this contains a secret for zeebe test environment, once the redis is moved to sit will be updating it
> Helm values for GOV-417

- PostmanCollections/Payment Hub.json
- helm/ph-ee-engine/templates/connector-bulk/deployment.yaml
- helm/ph-ee-engine/values.yaml
Updated postman tests
add template and default for new variable
Parent PR: https://github.com/openMF/ph-ee-bulk-processor/pull/51
> Suggested Callback Time that is Resolved by Polling

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
- Redis Configuration
- Business Short Code Configuration
> Redis Configuration

- helm/ph-ee-engine/connector-mock-paymentschema/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-paymentschema/templates/serviceaccount.yaml
- helm/ph-ee-engine/values.yaml
Created Deployment and service account for new service: https://github.com/fynarfin/ph-ee-connector-mock-payment-schema/
> GOV-338: Added deployment files for new mock payment schema service

- helm/ph-ee-engine/requirements.yaml
> adding condition for each dependency

- helm/ph-ee-engine/values.yaml
> adding flag for zeebe-cluster-helm

- helm/identity-account-mapper/Chart.yaml
- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/identity-account-mapper/account-mapper/templates/ingress.yaml
- helm/identity-account-mapper/account-mapper/templates/service.yaml
- helm/identity-account-mapper/account-mapper/templates/serviceaccount.yaml
- helm/identity-account-mapper/requirements.yaml
- helm/identity-account-mapper/values.yaml
* Added yaml files for Identity Account Mapper.
> Yaml files for Identity Account Mapper

- PostmanCollections/ES ILM Policy and Snapshot Register API.json
- PostmanCollections/Environment/ES_ILM_Policy_Snapshot_enviroment.json
* This PR includes the postman collection to create ILM Policy and elastic search.
> Elastic Search APIs

- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/connector-ams-mifos/templates/integration-test.yaml
- helm/ph-ee-engine/kafka/templates/service.yaml
- helm/ph-ee-engine/kafka/values.yaml
- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
Config changes related to Zeebe upgrade
[GOV-449](https://mifosforge.jira.com/browse/GOV-449)
[GOV-449]: https://mifosforge.jira.com/browse/GOV-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Upgrade zeebe to 8.1.1

- helm/ph-ee-engine/ams-paygops/templates/secret.yaml
- helm/ph-ee-engine/ams-paygops/templates/service.yaml
- helm/ph-ee-engine/ams-roster/templates/secret.yaml
- helm/ph-ee-engine/ams-roster/templates/service.yaml
- helm/ph-ee-engine/connector-ams-mifos/templates/service.yaml
- helm/ph-ee-engine/connector-bulk/templates/secret.yaml
- helm/ph-ee-engine/connector-bulk/templates/service.yaml
- helm/ph-ee-engine/connector-channel/templates/service.yaml
- helm/ph-ee-engine/connector-gsma/templates/service.yaml
- helm/ph-ee-engine/connector-mojaloop/templates/service.yaml
- helm/ph-ee-engine/connector-mpesa/templates/secret.yaml
- helm/ph-ee-engine/connector-mpesa/templates/service.yaml
- helm/ph-ee-engine/connector-notifications/templates/service.yaml
- helm/ph-ee-engine/connector-slcb/templates/secret.yaml
- helm/ph-ee-engine/connector-slcb/templates/service.yaml
- helm/ph-ee-engine/kafka/templates/service.yaml
- helm/ph-ee-engine/message-gateway/templates/secret.yaml
- helm/ph-ee-engine/message-gateway/templates/service.yaml
- helm/ph-ee-engine/operations-app/templates/secret.yaml
- helm/ph-ee-engine/operations-app/templates/service.yaml
- helm/ph-ee-engine/operations-importer-rdbms/templates/secret.yaml
- helm/ph-ee-engine/operations-web/templates/service.yaml
- helm/ph-ee-engine/zeebe-ops/templates/service.yaml
* Fixed enable condition for service and secrets 
* Added {{- if .Values.enabled -}} condition for each service and secret in templates.
> Fixed enable condition for service and secrets

- helm/identity-account-mapper/account-mapper/Chart.yaml
- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/identity-account-mapper/account-mapper/templates/ingress.yaml
- helm/identity-account-mapper/account-mapper/templates/service.yaml
- helm/identity-account-mapper/account-mapper/values.yaml
- helm/identity-account-mapper/requirements.yaml
- helm/identity-account-mapper/values.yaml
* FIx for Identity Mapper Ingress and deployment Issue GOV-210.
> GOV-210 Identity Account Mapper yaml files

- helm/ph-ee-engine/templates/deployment.yaml
- helm/ph-ee-engine/templates/serviceaccount.yaml
- helm/ph-ee-engine/values.yaml
Adding deployemt for new service
> GOV-338 Adding deployment for mock payment schema

- helm/g2p-sandbox/Chart.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
* updated g2psandbox chart to default version (v0.0.0)
> update g2psandbox chart to default version

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-bulk/templates/ingress.yaml
- helm/ph-ee-engine/connector-bulk/values.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/service.yaml
- helm/ph-ee-engine/connector-channel/values.yaml
- helm/ph-ee-engine/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-323) Description 
* Fix Bulk Ingress
* Bulk Deduplication enabling
* Fix Channel ingress for TLS
* Fix Channel server_ssl_key_password and server_ssl_key_store_password
* Update Channel and Bulk ports 
> PHEE-323 remove ops-web ingress classname

- helm/ph-ee-engine/connector-channel/values.yaml
* [Updated the path prefix of ingress PHEE-327](https://fynarfin.atlassian.net/browse/PHEE-327)
> PHEE-327 Updated the path prefix

- helm/g2p-sandbox/config/application-bb.properties
- helm/g2p-sandbox/config/application-fin12.properties
- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-bulk/values.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-mpesa/templates/deployment.yaml
- helm/ph-ee-engine/connector-mpesa/values.yaml
- helm/ph-ee-engine/connector-notifications/templates/deployment.yaml
- helm/ph-ee-engine/connector-notifications/values.yaml
- helm/ph-ee-engine/connector-slcb/templates/deployment.yaml
- helm/ph-ee-engine/connector-slcb/values.yaml
- helm/ph-ee-engine/values.yaml
- helm/ph-ee-engine/zeebe-ops/templates/_helpers.tpl
- helm/ph-ee-engine/zeebe-ops/templates/deployment.yaml
- helm/ph-ee-engine/zeebe-ops/values.yaml
(https://mifosforge.jira.com/jira/software/c/projects/GOV/issues/GOV-525?filter=allissues) Description
* Added Image name in ph-ee-engine chart.
* Disabled mock-payment-schema in ph-ee-engine
* Enabled mock payment schema in g2psandbox chart
* Updated Zeebe pod release 
> GOV-525 Stabilising G2pSandbox Helm Chart

- helm/ph-ee-engine/values.yaml
[PHEE-356 Increase the request and limit for ams_mifos in env-template](https://fynarfin.atlassian.net/browse/PHEE-356?atlOrigin=eyJpIjoiNmIzOTcxNTE1NmE2NDlhZmIwZTg3OTI3ODRmMjI4ZTYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-356 Increase the request and limit for ams_mifos in env-template

- helm/ph-ee-engine/operations-importer-rdbms/templates/deployment.yaml
Jira link: [PHEE-358](https://fynarfin.atlassian.net/browse/PHEE-358)
[PHEE-358]: https://fynarfin.atlassian.net/browse/PHEE-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add AWS secret and access key for Importer RDBMS

- .circleci/config.yml
- [PHEE-363 Add gradlew test for @AMSIntegration suite](https://fynarfin.atlassian.net/browse/PHEE-363?atlOrigin=eyJpIjoiNDg5MzdjYTIxYjA1NGRiYjhlNzY0MjE0MTQ5NDJhMjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-363 Added gradlew test in CI config for @AMSIntegration suite

- .circleci/config.yml
- [PHEE-366 Update region and parameterize in contexts](https://fynarfin.atlassian.net/browse/PHEE-366?atlOrigin=eyJpIjoiZjA3MmE3NWRkMjgyNDgyMDljYTY2OWMzNWFjZTAwYWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-366 Update region and parameterize in contexts

- helm/ph-ee-engine/values.yaml
[PHEE-376 Change S3 bucket name in env-template](https://fynarfin.atlassian.net/browse/PHEE-376?atlOrigin=eyJpIjoiNWI0YWNjZTM1ZjJhNGJiY2JmNTRiM2M3ZmM2YTg2OWQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-376 Change S3 bucket name in env-template

- helm/ph-ee-engine/zeebe-ops/templates/deployment.yaml
Updated zeebe broker contact-point in zeebe ops deployment file
> Updated zeebe broker point in zeebe ops deployment file

- helm/ph-ee-engine/connector-mock-paymentschema/templates/ingress.yaml
- helm/ph-ee-engine/connector-mock-paymentschema/values.yaml
This PR would add ingress for Mock Payment Schema.
Jira link: [GOV-301](https://mifosforge.jira.com/browse/GOV-301)
[GOV-301]: https://mifosforge.jira.com/browse/GOV-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-301: Add ingress for mock payment schema

- helm/ph-ee-engine/connector-mock-paymentschema/templates/deployment.yaml
- helm/ph-ee-engine/values.yaml
- added env variables for zeebe contactpoint
- added env variables for mock failure percentage
https://fynarfin.atlassian.net/browse/PHEE-395?atlOrigin=eyJpIjoiZTUxZmY2OGRjZWFmNGMzMWJkNjE0MTk1NDQ1YzY0YjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> [PHEE-395] Added environment variables

- helm/ph-ee-engine/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-383)
* Updated external dependencies with default StorageClassName with gp2. 
> #PHEE-383 StorageclassName for external dependencies 

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
(https://fynarfin.atlassian.net/browse/PHEE-401)
[Description]
* Change the backend service to mps
> #PHEE-401 G2psandbox chart

- .circleci/config.yml
> add-ngrok-to-test-gov

- helm/g2p-sandbox/Chart.yaml
- helm/g2p-sandbox/requirement.yaml
- helm/g2p-sandbox/values.yaml
- helm/identity-account-mapper/account-mapper/Chart.yaml
- helm/identity-account-mapper/account-mapper/templates/clusterrole.yaml
- helm/identity-account-mapper/account-mapper/templates/clusterrolebinding.yaml
- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/identity-account-mapper/account-mapper/templates/ingress.yaml
- helm/identity-account-mapper/account-mapper/templates/rolebinding.yaml
- helm/identity-account-mapper/account-mapper/templates/service.yaml
- helm/identity-account-mapper/account-mapper/values.yaml
- helm/identity-account-mapper/values.yaml
- helm/ph-ee-engine/connector-channel/values.yaml
* Deployment file fix for identity account mapper. [GOV-517](https://mifosforge.jira.com/browse/GOV-517?atlOrigin=eyJpIjoiZmNhYzYyNWY5MDYzNDhjOWEzYTI2Y2U2ZGVlNjBkZTkiLCJwIjoiaiJ9)
[GOV-517]: https://mifosforge.jira.com/browse/GOV-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-517 Deployment file fix for Identity Account Mapper

- PostmanCollections/Payment Hub.json
* Fixed postman collection import issue
[PHEE-411](https://fynarfin.atlassian.net/browse/PHEE-411)
[PHEE-411]: https://fynarfin.atlassian.net/browse/PHEE-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-411 Fixed Postman collection import issue

- .circleci/config.yml
- helm/ph-ee-engine/values.yaml
* Added postgres database for kong.
> Gov 285 Patch changes

- helm/g2p-sandbox/Chart.yaml
- helm/g2p-sandbox/requirement.yaml
- helm/g2p-sandbox/values.yaml
- helm/identity-account-mapper/account-mapper/Chart.yaml
- helm/identity-account-mapper/account-mapper/templates/clusterrole.yaml
- helm/identity-account-mapper/account-mapper/templates/clusterrolebinding.yaml
- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/identity-account-mapper/account-mapper/templates/ingress.yaml
- helm/identity-account-mapper/account-mapper/templates/rolebinding.yaml
- helm/identity-account-mapper/account-mapper/templates/service.yaml
- helm/identity-account-mapper/account-mapper/values.yaml
- helm/identity-account-mapper/values.yaml
- helm/ph-ee-engine/connector-channel/values.yaml
* Identity Account Mapper Deployment files.
> Identity Account Mapper

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-bulk/templates/service.yaml
- helm/ph-ee-engine/connector-bulk/values.yaml
- helm/ph-ee-engine/values.yaml
[GOV-287](https://mifosforge.jira.com/browse/GOV-287)
[GOV-287]: https://mifosforge.jira.com/browse/GOV-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV 287: Removed the nginx annotation for bulk in g2p-sandbox chart

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
[PHEE-417 Upgrade kubernetes version 1.24 to 1.27](https://fynarfin.atlassian.net/browse/PHEE-417?atlOrigin=eyJpIjoiN2EzZDJlMjA3YjU4NDI5YzgxY2U0Y2ExYjliMDQ3MGMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-417 Upgrade kubernetes version 1.24 to 1.27

- helm/g2p-sandbox/values.yaml
*Adding lion tenant in channel and zeebe-ops
> PHEE-431 Adding lion tenant

- helm/ph-ee-engine/values.yaml
[PHEE-430 disable zeebe-operate from paymenthub.](https://fynarfin.atlassian.net/browse/PHEE-430?atlOrigin=eyJpIjoiNGY2YWVhMGQzNDMyNDExMjljODFmMzViNDhmNzlmYzUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-430 disable zeebe-operate from paymenthub.

- helm/g2p-sandbox/values.yaml
> PHEE-431 Script to create lion db

- PostmanCollections/Payment Hub.json
> Update IAM and Vouchers APIs in Postman Collection

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
* Update the Elastic-search version
> update the elastic search version

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
* Roll back to previous versions of elastic search and camunda-platform
> revert back to main release

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
> testing camunda version and reverting ES

- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
> testing ES 7.17.1

- helm/ph-ee-engine/connector-channel/templates/service.yaml
[PHEE-439]
[PHEE-439]: https://fynarfin.atlassian.net/browse/PHEE-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-439-Channel service port changed to 8443

- helm/ph-ee-engine/values.yaml
* Update camunda-platform image version to 8.2.8
> test with camunda-platform image-8.2.8

- helm/ph-ee-engine/requirements.yaml
> revert the camunda-platform and ES version

- helm/ph-ee-engine/templates/tests/integration-test.yaml
> New release

- helm/ph-ee-engine/message-gateway/templates/deployment.yaml
https://fynarfin.atlassian.net/browse/PHEE-441) 
#Description
* fixed message-gateway zeebe-BrokerContactPoint
* configured Zeebe-BCP in the helm chart to point to release-name
> PHEE_441 message-gateway zeebe-BCP fix

- helm/ph-ee-engine/templates/tests/integration-test.yaml
* Added Voucher contact point 
*  Added http for service end point for IAM
> add voucher contact point and iam

- helm/ph-ee-engine/values.yaml
> configure integration test values

- helm/ph-ee-engine/templates/tests/integration-test.yaml
> configure bulk url

- helm/ph-ee-engine/templates/tests/integration-test.yaml
> add loglevel debug

- helm/g2p-sandbox/values.yaml
> bullseye image for iam

- helm/ph-ee-engine/templates/tests/integration-test.yaml
- helm/ph-ee-engine/values.yaml
* Updated Identity accountMapper to bullseye docker image  v1.3.1
* Updated mockPaymentSchema to bullseye docker image  v1.3.1
> Bullseye image for iam and mps

- .circleci/config.yml
- helm/g2p-sandbox/Chart.yaml
- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/connector-channel/templates/service.yaml
- helm/ph-ee-engine/templates/tests/integration-test.yaml
- helm/ph-ee-engine/values.yaml
> Update release tag 1.10.1

- helm/ph-ee-engine/connector-ams-mifos/templates/service.yaml
[PHEE-444 Create an ingress that points to ams mifos mock server.](https://github.com/openMF/ph-ee-env-labs/pull/180)
> PHEE-444 Create an ingress that points to ams mifos mock server.

- helm/g2p-sandbox/values.yaml
* Added CORS ingress annotations to operations-app and voucher
> Ingress CORS Annotations to ops-web and voucher

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-bulk/values.yaml
- helm/ph-ee-engine/values.yaml
> GOV-517 Adding IAM hostname in bulk

- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/ph-ee-engine/ams-paygops/templates/deployment.yaml
- helm/ph-ee-engine/ams-roster/templates/deployment.yaml
- helm/ph-ee-engine/connector-ams-mifos/templates/deployment.yaml
- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/service.yaml
- helm/ph-ee-engine/connector-channel/values.yaml
- helm/ph-ee-engine/connector-gsma/templates/deployment.yaml
- helm/ph-ee-engine/connector-gsma/values.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/values.yaml
- helm/ph-ee-engine/connector-mojaloop/templates/deployment.yaml
- helm/ph-ee-engine/connector-mojaloop/values.yaml
- helm/ph-ee-engine/connector-mpesa/templates/deployment.yaml
- helm/ph-ee-engine/connector-mpesa/values.yaml
- helm/ph-ee-engine/connector-notifications/templates/deployment.yaml
- helm/ph-ee-engine/connector-notifications/values.yaml
- helm/ph-ee-engine/connector-slcb/templates/deployment.yaml
- helm/ph-ee-engine/connector-slcb/templates/service.yaml
- helm/ph-ee-engine/message-gateway/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/values.yaml
- helm/ph-ee-engine/operations-importer-es/templates/deployment.yaml
- helm/ph-ee-engine/operations-importer-rdbms/templates/deployment.yaml
- helm/ph-ee-engine/operations-web/templates/deployment.yaml
- helm/ph-ee-engine/values.yaml
- helm/ph-ee-engine/zeebe-ops/templates/deployment.yaml
* Check dependency service health before pod initialization.
> GOV-134 livness/readiness check

- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/ph-ee-engine/ams-paygops/templates/deployment.yaml
- helm/ph-ee-engine/ams-roster/templates/deployment.yaml
- helm/ph-ee-engine/connector-ams-mifos/templates/deployment.yaml
- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/service.yaml
- helm/ph-ee-engine/connector-channel/values.yaml
- helm/ph-ee-engine/connector-gsma/templates/deployment.yaml
- helm/ph-ee-engine/connector-gsma/values.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/values.yaml
- helm/ph-ee-engine/connector-mojaloop/templates/deployment.yaml
- helm/ph-ee-engine/connector-mojaloop/values.yaml
- helm/ph-ee-engine/connector-mpesa/templates/deployment.yaml
- helm/ph-ee-engine/connector-mpesa/values.yaml
- helm/ph-ee-engine/connector-notifications/templates/deployment.yaml
- helm/ph-ee-engine/connector-notifications/values.yaml
- helm/ph-ee-engine/connector-slcb/templates/deployment.yaml
- helm/ph-ee-engine/connector-slcb/templates/service.yaml
- helm/ph-ee-engine/message-gateway/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/values.yaml
- helm/ph-ee-engine/operations-importer-es/templates/deployment.yaml
- helm/ph-ee-engine/operations-importer-rdbms/templates/deployment.yaml
- helm/ph-ee-engine/operations-web/templates/deployment.yaml
- helm/ph-ee-engine/values.yaml
- helm/ph-ee-engine/zeebe-ops/templates/deployment.yaml
Reverts openMF/ph-ee-env-template#253
> Revert "GOV-134 livness/readiness check"

- helm/ph-ee-engine/message-gateway/templates/deployment.yaml
[Zeebe-contact-point issue in message-gateway service](https://fynarfin.atlassian.net/browse/PHEE-400?atlOrigin=eyJpIjoiOTFhMDdiZThhMjkyNGU3MmE3NjE4YjYyNjZhMDU4MjgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
* Fixed Zeebe-contact-point issue in message-gateway service
>  PHEE-400 Zeebe-Contact-point fix in message-gateway service

- helm/ph-ee-engine/operations-importer-rdbms/templates/deployment.yaml
- helm/ph-ee-engine/operations-importer-rdbms/values.yaml
- helm/ph-ee-engine/values.yaml
* Added bucket-name and aws.region as env param for importer-rdbms.
[PHEE-478](https://fynarfin.atlassian.net/browse/PHEE-478)
[GOV-325](https://mifosforge.jira.com/browse/GOV-325)
[PHEE-478]: https://fynarfin.atlassian.net/browse/PHEE-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GOV-325]: https://mifosforge.jira.com/browse/GOV-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Phee-478: Added bucket name and region as env param

- Keycloak/paymenthub-realm.json
- Keycloak/readme.md
* Exported and added current `paymethub` realm configuration.
* Created readme containing the below 3 sections.
* How to export realm configuration
* How to import realm configuration
* How to see/generate client secret
[phee-481](https://fynarfin.atlassian.net/browse/PHEE-481)
[**Use this link to see the rendered version of markdown updated in this PR**](https://github.com/danishjamal104/ph-ee-env-template/blob/PHEE-481/Keycloak/readme.md)
> PHEE-481: Added paymenthub keycloak realm configuration and related documentation

- .circleci/config.yml
- .circleci/docker-image-availability-check-and-upgrade.yml
[PHEE-490 Publish helm chart with jira ticket from circleci](https://fynarfin.atlassian.net/browse/PHEE-490?atlOrigin=eyJpIjoiNTgxMTdiZWM4MGM0NGExZWExYmFiYzk3MzQ0OWJiMTUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-490] Publish helm chart with jira ticket from circleci

- .circleci/docker-image-availability-check-and-upgrade.yml
[PHEE-490 Publish helm chart with jira ticket from circleci](https://fynarfin.atlassian.net/browse/PHEE-490?atlOrigin=eyJpIjoiMDAwNWMwNjNmN2NhNGUyZWExZDU4NWIwNGU3MmU5ZjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [phee-490]fix for image invalid format issue

- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/templates/deployment.yaml
- helm/ph-ee-engine/values.yaml
> [PHEE-493] Update the pod termination grace period and liveness/readiness period

- .circleci/config.yml
- .circleci/docker-image-availability-check-and-upgrade.yml
[PHEE-500 Apply check for chart availability during deployment.](https://fynarfin.atlassian.net/browse/PHEE-500?atlOrigin=eyJpIjoiMzZhZGY5NzJjMzlkNDhkYWI5MWYzMzY3MTM2MTE1MWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-500] Apply check for chart availability during deployment.

- helm/ph-ee-engine/connector-mojaloop/templates/deployment.yaml
[PHEE-496 Update ml-connector config](https://fynarfin.atlassian.net/browse/PHEE-496?atlOrigin=eyJpIjoiZTIzZTY5ODA2N2Y1NDAyY2JhZDU3YWJjOTkwODkxNjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-496] Update ml-connector config

- .circleci/config.yml
- helm/identity-account-mapper/account-mapper/values.yaml
- helm/ph-ee-engine/templates/tests/integration-test.yaml
- helm/ph-ee-engine/values.yaml
[PHEE-502 Fix integration test for v1.11.0 release.](https://fynarfin.atlassian.net/browse/PHEE-502?atlOrigin=eyJpIjoiOTkzNTcyZWQyMjBhNGU0Yzk0OGNhOTU3MzU3NzA3NGEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-502] Fix integration test for v1.11.0 release.

- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/templates/deployment.yaml
[PHEE-501 Adding the place holder for termination grace period for channel, b…](https://fynarfin.atlassian.net/browse/PHEE-501?atlOrigin=eyJpIjoiODBjZDE5OTRmMGFjNDJiY2E1MjVhZGIzYzYwNjE2YjgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-501] Adding the place holder for termination grace period

- Keycloak/readme.md
[Refer this link for the preview of markdown](https://github.com/danishjamal104/ph-ee-env-template/blob/master/Keycloak/readme.md)
> Updated keycloak readme

- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/templates/deployment.yaml
> [PHEE-501] Updating the deployment for the termination grace place holder

- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-channel/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/templates/deployment.yaml
> [PHEE-501] Revert "Updating the deployment for the termination grace place holder"

- helm/ph-ee-engine/connector-mock-payment-schema/templates/service.yaml
[PHEE-516 Change mock payment schema service spec type to Loadbalancer](https://fynarfin.atlassian.net/browse/PHEE-516?atlOrigin=eyJpIjoiMGJlYTAzNGVlMDYzNGNiYWJjZGVjNzc3MDQwZDg4MmMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-516] Change mock payment schema service spec type to Loadbalancer

- helm/g2p-sandbox/values.yaml
> bulk-port-change

- helm/ph-ee-engine/connector-gsma/templates/service.yaml
- helm/ph-ee-engine/connector-mojaloop/templates/ingress.yaml
- helm/ph-ee-engine/connector-mojaloop/templates/service.yaml
- helm/ph-ee-engine/connector-notifications/templates/ingress.yaml
- helm/ph-ee-engine/connector-notifications/templates/service.yaml
- helm/ph-ee-engine/zeebe-ops/templates/ingress.yaml
- helm/ph-ee-engine/zeebe-ops/templates/service.yaml
* [GOV-134 Requires the Payment Building Block to degrade gracefully under cond…](https://mifosforge.jira.com/browse/GOV-134?atlOrigin=eyJpIjoiYjMyMDVlOTczYjVmNDYyNGI0MWRjZjQ1NWNkMmFkZDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [GOV-134]  Updated the service and ingress for services to work with actuator

- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/ph-ee-engine/connector-mock-payment-schema/templates/deployment.yaml
- helm/ph-ee-engine/vouchers/templates/deployment.yaml
> [GOV-134] Added liveness readiness check for restart on memory issues

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-bulk/templates/deployment.yaml
- helm/ph-ee-engine/connector-bulk/templates/secret.yaml
- helm/ph-ee-engine/connector-bulk/values.yaml
- helm/ph-ee-engine/connector/templates/deployment.yaml
- helm/ph-ee-engine/operations-importer-rdbms/templates/deployment.yaml
- helm/ph-ee-engine/operations-importer-rdbms/values.yaml
- helm/ph-ee-engine/requirements.yaml
- helm/ph-ee-engine/values.yaml
[PHEE-494 Add Minio to the ph ee engine helm chart](https://fynarfin.atlassian.net/browse/PHEE-494?atlOrigin=eyJpIjoiZjQ4MjNhZmJmZTdlNDEyZGJhNTAyYzE0MjcyZjkwMWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-494] Add-minio-to-helm-chart

- PostmanCollections/Payment Hub.json
* https://mifosforge.jira.com/browse/GOV-279
> [GOV-279] Resolved conflict in potman collectoion

- helm/ph-ee-engine/values.yaml
[PHEE-536 Enable kafka external access](https://fynarfin.atlassian.net/browse/PHEE-536?atlOrigin=eyJpIjoiNTVjNWU4ZDBlMzQzNDMzMmJjMmI2MjhhMTYxMDU5ZGEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-536] Enable kafka external access

- helm/ph-ee-engine/values.yaml
[PHEE-539 Make kafka work with replica count 1](https://fynarfin.atlassian.net/browse/PHEE-539?atlOrigin=eyJpIjoiNTM4NWUyOTYyYmM2NDZkYjhlYjNlMTcwMTk3NGRjN2QiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-539] Make kafka work with replica count 1

- .circleci/config.yml
- helm/ph-ee-engine/templates/post-installation-job/job.yaml
- helm/ph-ee-engine/templates/tests/integration-test-ams.yaml
- helm/ph-ee-engine/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-548)
- Ephemeral Instance 
-  Using resource_class: Xlarge 
-  Install tools to set up Minikube
-  Run Minikube
-  Helm deploy 
-  Post-installation steps
-  Helm test
- Fetch reports and store artifacts
> [PHEE-548] Minikube helm chart install

- .circleci/config.yml
- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/templates/tests/integration-test-gov.yaml
- helm/ph-ee-engine/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-548)
> [PHEE-548] Ephemeral Instance Helm test fix

- .circleci/config.yml
- helm/ph-ee-engine/templates/tests/integration-test-ams.yaml
- helm/ph-ee-engine/templates/tests/integration-test-gov.yaml
- helm/ph-ee-engine/values.yaml
> [PHEE-548] integration-test-image-config

- .circleci/config.yml
> [PHEE-548] integration-test-report-fetch-fix

- helm/ph-ee-engine/vouchers/templates/deployment.yaml
- helm/ph-ee-engine/vouchers/values.yaml
[PHEE-583 Voucher paymentMobality not found.](https://fynarfin.atlassian.net/browse/PHEE-583?atlOrigin=eyJpIjoiNDhmNTRiNWI2OTVlNDkwNTk1ZWM2ZmQ1ZGZiY2RiYjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-583] Voucher paymentMobality not found

- helm/g2p-sandbox/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-601)
- Include the  HTTP headers in its response to allow CORS for new services viz, Billpay, crm etc
> [PHEE-601] Include the  HTTP headers in its response to allow CORS

- PostmanCollections/Environment/PHEE_G2P_Demo.postman_environment.json
- PostmanCollections/Environment/SIT.json
- PostmanCollections/Payment Hub.json
[PHEE-604 Update Postman Collection for Voucher and IAM APIs](https://fynarfin.atlassian.net/browse/PHEE-604?atlOrigin=eyJpIjoiOWYwMzE4YjMzNDBmNGM2OTg4MzQzMTkwYTgxODM4M2YiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-604] Fixed voucher and IAM APIs collection

- helm/identity-account-mapper/account-mapper/templates/deployment.yaml
- helm/identity-account-mapper/account-mapper/values.yaml
- helm/ph-ee-engine/values.yaml
- helm/ph-ee-engine/vouchers/templates/deployment.yaml
- helm/ph-ee-engine/vouchers/values.yaml
[PHEE-608 Separate voucher callback part from check-transfer-status worker.](https://fynarfin.atlassian.net/browse/PHEE-608?atlOrigin=eyJpIjoiNzhlOGZhZDNkMDNkNDVlN2I4MzU0MjYzNjc2NjUwZDEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-608] Separate voucher callback part from check-transfer-status worker

- .circleci/config.yml
- helm/ph-ee-engine/templates/post-installation-job/job.yaml
https://fynarfin.atlassian.net/browse/PHEE-571)
> [PHEE-571] Set a namespace variable in the job

- helm/ph-ee-engine/templates/post-installation-job/job.yaml
(https://fynarfin.atlassian.net/browse/PHEE-612)
> [PHEE-612] Run int-test on tag and fetch the report

- .circleci/config.yml
- helm/g2p-sandbox/values.yaml
> [testing] adding sleep

- PostmanCollections/Payment Hub.json
[PHEE-613 Add bill-pay APIs to PH Postman Collection](https://fynarfin.atlassian.net/browse/PHEE-613?atlOrigin=eyJpIjoiZGRkYjhlMWE2NmVlNGUwOGE5MGQxOWE3M2RhYTFlNWYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-613] Add bill-pay APIs to PH Postman Collection

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/values.yaml
https://fynarfin.atlassian.net/browse/PHEE-601)
- Add cors plugin for the kong
- Add headers for Bulk and Voucher
> [PHEE-601] CORS fix and cors plugin for kong

- PostmanCollections/Payment Hub.json
[PHEE-632 Add callback as an example in batch transaction API](https://fynarfin.atlassian.net/browse/PHEE-632?atlOrigin=eyJpIjoiNTk2NDIyYzFkMmRiNGQxZWI2ODRkOWEzZWM1MWUyYmIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-632] Add callback as an example in batch transaction API

- helm/g2p-sandbox/values.yaml
https://fynarfin.atlassian.net/browse/PHEE-601)
> [PHEE-601] Update header for ops-app 

- helm/ph-ee-engine/values.yaml
> [v1.6.0-rc.5] update the integration test and operations app

- helm/ph-ee-engine/operations-web/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-625)
- Specify the values for environment variables in operations-web 
- Environment variables for Bulk import batches
> [PHEE-625] Configure helm Values for ops-web

- helm/g2p-sandbox-security/values.yaml
> disbaled the jobs for security chart

- PostmanCollections/Payment Hub.json
[PHEE-643 Voucher Code Sync with Google API docs](https://fynarfin.atlassian.net/browse/PHEE-643?atlOrigin=eyJpIjoiM2YyMmFjZDIyMTFiNGUyYmIxNzZmZTU1YmNkYmYzMmYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-643] Update voucher APIs method

- PostmanCollections/Payment Hub.json
[PHEE-647 Add Postman API Doc for Voucher](https://fynarfin.atlassian.net/browse/PHEE-647?atlOrigin=eyJpIjoiYmFiZWJlMzUwMmUzNDhlZDk1MjVkOTY0OTJkMjg2MGMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-647] Add examples for Voucher API

- helm/ph-ee-engine/operations-app/templates/deployment.yaml
- helm/ph-ee-engine/operations-app/values.yaml
[PHEE-648 Fix AWS s3 status code 404 issue.](https://fynarfin.atlassian.net/browse/PHEE-648?atlOrigin=eyJpIjoiYmFjMGZmOTFlZTVhNGI0ZmI1ZmM4OTNmMzkzYzAwMGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-648] Fix AWS s3 status code 404 issue.

- helm/g2p-sandbox-security/Chart.yaml
- helm/g2p-sandbox-security/values.yaml
[PHEE-656 Graphana kong dashboard](https://fynarfin.atlassian.net/browse/PHEE-656?atlOrigin=eyJpIjoiN2RhMTExY2Q4MDk5NDVkYWE2ZTIxM2JkNzY2NmE3OTYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-656] Graphana kong dashboard

- PostmanCollections/Payment Hub.json
[PHEE-661 Update and add examples for GSMA transaction API in postman collection.](https://fynarfin.atlassian.net/browse/PHEE-661?atlOrigin=eyJpIjoiN2FiODA5MDZiY2IyNDAzNjgyMWNmY2Q1Zjc5ZTNmYWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-661] Update and add examples for GSMA transaction API in postman collection.

- helm/ph-ee-engine/values.yaml
Reverts openMF/ph-ee-env-template#433
Reverting this PR due to issues in HELM chart
> Revert "[PHEE-667] Enable prometheus service monitor in chart and export data in metri…"

- PostmanCollections/Environment/SIT.json
- PostmanCollections/Payment Hub.json
> [phee-665] Update Bill-Pay APIs

- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/connector-bill-pay/values.yaml
> [GOV-83New] Tcs for status API

- helm/g2p-sandbox/values.yaml
> [PHEE-660] sql url change for IAM

- .circleci/config.yml
- helm/g2p-sandbox-security/Chart.yaml
- helm/g2p-sandbox/Chart.yaml
- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/templates/post-installation-job/job.yaml
- helm/ph-ee-engine/values.yaml
> release process v1.14.0

- .circleci/config.yml
- helm/g2p-sandbox-security/Chart.yaml
- helm/g2p-sandbox/Chart.yaml
- helm/g2p-sandbox/values.yaml
- helm/ph-ee-engine/Chart.yaml
- helm/ph-ee-engine/templates/post-installation-job/job.yaml
- helm/ph-ee-engine/values.yaml
> release process v1.13.1

- helm/ph-ee-engine/templates/post-installation-job/job.yaml
[PHEE-681 Fix netcat issue with the post-installation job](https://fynarfin.atlassian.net/browse/PHEE-681?atlOrigin=eyJpIjoiMTEyYmZjZGZhMzA0NDJlMzhlZTAxZTlhNmQ5ZDJkYjMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-681] Fix netcat issue with the post-installation job

- .circleci/config.yml
- helm/ph-ee-engine/templates/post-installation-job/job.yaml
- helm/ph-ee-engine/templates/tests/_helpers.tpl
- helm/ph-ee-engine/values.yaml
…art.
[PHEE-679 Update env-template pipline to use ph-ee-g2p-sandbox-ci chart.](https://fynarfin.atlassian.net/browse/PHEE-679?atlOrigin=eyJpIjoiYWZlYWI1NjRkYzIyNGJjNmJmZTIwN2JmZDYxNWNhMDEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-679] Update env-template pipline to use ph-ee-g2p-sandbox-ci chart.

- .circleci/config.yml
> fix for ci build step

- PostmanCollections/Payment Hub.json
> [PHEE-697] Adding payee dfsp id header in batch and transfer API postman collection

- helm/g2p-sandbox/config/application-bb.properties
[PHEE-700 GovStack Demo Test Cases](https://fynarfin.atlassian.net/browse/PHEE-700?atlOrigin=eyJpIjoiMGRlZThlMDhlZjYxNDI2MmJiMTc0ZjYxZjNmNmUyYWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-700] Configuration for Different Ministry in bulk
